package view;

import controller.RewardController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ContainerAdapter;

public class RewardPanel extends JFrame {
    //region Components
    private JPanel rewardTitlePanel;
    private JPanel hiddenPanel;
    private JPanel rewardPanel;
    //endregion

    RewardController controller;

    public RewardPanel(RewardController controller) {
        this.controller = controller;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rewardPanel = new JPanel();
        rewardPanel.setLayout(new GridBagLayout());
        rewardTitlePanel = new JPanel();
        rewardTitlePanel.setLayout(new GridBagLayout());
        rewardTitlePanel.setAlignmentX(0.5f);
        rewardTitlePanel.setAlignmentY(0.5f);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.NORTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rewardPanel.add(rewardTitlePanel, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Image");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        rewardTitlePanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        rewardTitlePanel.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Description");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        rewardTitlePanel.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Price");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        rewardTitlePanel.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Available");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        rewardTitlePanel.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("Remaining");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        rewardTitlePanel.add(label6, gbc);
        final JLabel label7 = new JLabel();
        label7.setHorizontalTextPosition(11);
        label7.setText("Level");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        rewardTitlePanel.add(label7, gbc);
        final JLabel label8 = new JLabel();
        label8.setHorizontalAlignment(0);
        label8.setHorizontalTextPosition(0);
        label8.setText("Edit");
        gbc = new GridBagConstraints();
        gbc.gridx = 7;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rewardTitlePanel.add(label8, gbc);
        final JLabel label9 = new JLabel();
        label9.setHorizontalAlignment(0);
        label9.setHorizontalTextPosition(0);
        label9.setText("Remove");
        gbc = new GridBagConstraints();
        gbc.gridx = 8;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rewardTitlePanel.add(label9, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rewardPanel;
    }

}
